services:
  db:
    image: postgres
    container_name: postgres-realtimechat
    environment:
      POSTGRES_DB: realtimechatapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword123
    volumes:
      - realtimechat-pg-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
volumes:
  realtimechat-pg-data:
